spring:
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
      exclude: static/**,public/**,WEB-INF/**
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
  redis:
    database: 0
    host: 192.168.6.128
    password: ''
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle: 2
    port: 6379
    timeout: 5000
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
